In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Amazonbookreviews.csv")

# Create row-wise subsets
subset1 = df.iloc[:100]
subset2 = df.iloc[100:200]

print("Subset 1:")
print(subset1.head())

print("\nSubset 2:")
print(subset2.head())

Subset 1:
       reviewerID      asin reviewername  helpful  \
0  A2SUAM1J3GNN3B   23456.0        SNEHA        2   
1  A2SUAN1J3GNN0C  879877.0      KARTHII        3   
2  A2SUAN1J3GNN7B   23456.0     SHASHANK        3   
3  A5SUAN1J3GNN9B   67578.0        NITIN        3   
4  A1SUAM1J3GNN3B     123.0      PRANOTI        3   

                                        reviewerText  overallRating  \
0  I bought this for my husband who plays the pia...            4.0   
1                                  good book to read            3.0   
2                                          high cost            2.5   
3                                    good useof book            2.2   
4                            I m happy with the book            3.0   

            Summary  UnixreviewTime  reviewTime  
0       SUBWAY SURF             NaN         NaN  
1            PILOT              NaN         NaN  
2   DRIVE IN HEAVEN             NaN         NaN  
3     SPORTS HEAVEN             NaN         

In [2]:
# Merge subsets row-wise
merged_df = pd.concat([subset1, subset2])

print("Merged Data:")
print(merged_df.head())

Merged Data:
       reviewerID      asin reviewername  helpful  \
0  A2SUAM1J3GNN3B   23456.0        SNEHA        2   
1  A2SUAN1J3GNN0C  879877.0      KARTHII        3   
2  A2SUAN1J3GNN7B   23456.0     SHASHANK        3   
3  A5SUAN1J3GNN9B   67578.0        NITIN        3   
4  A1SUAM1J3GNN3B     123.0      PRANOTI        3   

                                        reviewerText  overallRating  \
0  I bought this for my husband who plays the pia...            4.0   
1                                  good book to read            3.0   
2                                          high cost            2.5   
3                                    good useof book            2.2   
4                            I m happy with the book            3.0   

            Summary  UnixreviewTime  reviewTime  
0       SUBWAY SURF             NaN         NaN  
1            PILOT              NaN         NaN  
2   DRIVE IN HEAVEN             NaN         NaN  
3     SPORTS HEAVEN             NaN      

In [4]:
# Sort by review score (common column)
df_sorted = df.sort_values(by='overallRating', ascending=False)

print("Sorted Data:")
print(df_sorted.head())

Sorted Data:
        reviewerID      asin reviewername  helpful  \
9   1234ZSDFREQWEG   78761.0       SATISH        2   
11             NaN  876231.0        ROHIT        2   
10  9345GHIKLFLLED  321456.0         RAJU        2   
12  HGKIUYE345SFDG     987.0        MOHIT        2   
0   A2SUAM1J3GNN3B   23456.0        SNEHA        2   

                                         reviewerText  overallRating  \
9                                         many errors            5.0   
11                                          high vat             4.0   
10                                            no mini            4.0   
12                   the dealer is charged more money            4.0   
0   I bought this for my husband who plays the pia...            4.0   

                  Summary  UnixreviewTime  reviewTime  
9            DATA IS DATA             NaN         NaN  
11           FRIENDS HELP             NaN         NaN  
10  INDIA A MASSIVE POWER             NaN         NaN  
12   

In [5]:
df_transposed = df.T

print("Transposed Data:")
print(df_transposed.head())

Transposed Data:
                                                             0   \
reviewerID                                       A2SUAM1J3GNN3B   
asin                                                    23456.0   
reviewername                                              SNEHA   
helpful                                                       2   
reviewerText  I bought this for my husband who plays the pia...   

                             1               2                3   \
reviewerID       A2SUAN1J3GNN0C  A2SUAN1J3GNN7B   A5SUAN1J3GNN9B   
asin                   879877.0         23456.0          67578.0   
reviewername            KARTHII        SHASHANK            NITIN   
helpful                       3               3                3   
reviewerText  good book to read       high cost  good useof book   

                                   4                                       5   \
reviewerID             A1SUAM1J3GNN3B                         BA2345WERSDFRER   
asin     

In [6]:
# Create array
arr = np.arange(12)

# Reshape into 3x4
reshaped_arr = arr.reshape(3, 4)

print("Original Array:")
print(arr)

print("\nReshaped Array:")
print(reshaped_arr)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
